// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPlace struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type UpdatePlace struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}
